### ISSUE TITLE
Linking of dependencies not working.

### ISSUE THREAD

**Issue by evanheckert** [Ryan8765/deployqb#1]
Hi Ryan,

Thanks for this package! I ran npx create-react-app, entered yarn build, and attempted to deploy the default boilerplate to my qb app. Here's my qbcli.json: 

```{

  "urlQueryString": "",
  "repositoryId": "test2",
  "prodPrefix": "P",
  "devPrefix": "D",
  "dbid": "xxxxxxid",
  "realm": "company-name",
  "filesConf": [
    {
      "filename": "index.html",
      "path": "./build/",
      "dependencies": [
        1,
        2,
        3,
        5
      ],
      "isIndexFile": true
    },
    {
      "filename": "manifest.json",
      "path": "./build/"
    },
    {
      "filename": "main.d1b05096.chunk.css",
      "path": "./build/static/css/"
    },
    {
      "filename": "2.5b868ce8.chunk.js",
      "path": "./build/static/js/"
    },
    {
      "filename": "logo.5d5d9eef.svg",
      "path": "./build/static/media/"
    },
    {
      "filename": "main.94f03f89.chunk.js",
      "path": "./build/static/js/",
      "dependencies": [
        4
      ]
    }
  ],
  "launchProdPageId": 8
}

```

It uploads successfully, but won't let me set P_test2_index.html as default home page. Also, when I view P_test2_index.html, it's a blank page. Dev tools show: 
```

Refused to apply style from 'https://my-company-name.quickbase.com/static/css/main.d1b05096.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
2.5b868ce8.chunk.js:1 Failed to load resource: the server responded with a status of 404 ()
main.94f03f89.chunk.js:1 Failed to load resource: the server responded with a status of 404 ()
manifest.json:1 Failed to load resource: the server responded with a status of 404 ()
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
bqdaxwit6?a=dbpage&pageID=8:1 Refused to apply style from 'https://co-name.quickbase.com/static/css/main.d1b05096.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

```

Any suggestions?

**Comment by Ryan8765** [comment]
@evanheckert - sorry I have been so busy I am just seeing this.  I am assuming this has something to do with the build process.  Here is a stack overflow topic with similar issues:

https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type

Also - because you're building a react application with this, each time you build you will probably notice your build folder chunk files are named differently.  This is built into react for caching purposes, but may cause you to have these files loaded many times in Quick Base (essentially a new set of files in Quick Base each time you build and deploy).  Our guys have come up with a workaround for React that I will have to reach out to them to discuss if that would help.  

To be more help for you I'd really need to be able to access the files and fire it up on my side to debug a little more.  If there is a repo or something I could test out I may be able to help more.

Or could you send me an image of your linked files in your index.html file if the above isn't possible?  Just want to check the format.

**Comment by Ryan8765** [comment]
@evanheckert as luck would have it one of our developers ran into the exact same issue as this earlier today.  After debugging these were the steps that had to be taken:

1. Check your dependencies arrays in the qbcli.json and make sure these are all correct (remember that the first item in this array is index "0" and not "1").  Make sure these are all referencing the correct scripts.
2. Make sure that you are using the correct syntax in all of your <script> and <link> tags (example: ?act=dbpage&pagename=Kanban_DataLayer.js).  Using the command "deployqb genlinks" which shows all of the allowed links based off your dependencies array is the suggested method.  Copy and paste these into your code so as to not make a mistake when setting these up.
